import = [
    "~/.config/alacritty/themes/_active.toml"
]

[env]
TERM = "xterm-256color"


[window]
padding.x = 1
padding.y = 1
dynamic_padding = true

decorations = "None"
dynamic_title = true

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
normal.family = "DroidSansM Nerd Font"

size = 14
