# [general]
import = [
    "~/.config/alacritty/themes/_active.toml"
]

[env]
TERM = "xterm-256color"


[window]
# padding.x = 10
# padding.y = 10
# dynamic_padding = true

decorations = "None"
# dynamic_title = true

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "VictorMono Nerd Font Mono"
# normal.family = "UbuntuMono Nerd Font Mono"
normal.family = "DroidSansMono Nerd Font"

size = 14
