import = [
    # "~/.config/alacritty/themes/themes/coolnight.toml"
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/themes/solarized_light.toml"
    "~/.config/alacritty/themes/themes/solarized_osaka.toml"
    # "~/.config/alacritty/themes/themes/nord_light.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"


[window]
padding.x = 1
padding.y = 1
dynamic_padding = true

decorations = "None"
dynamic_title = true

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "VictorMono Nerd Font Mono"
#normal.family = "UbuntuMono Nerd Font Mono"
#normal.family = "EnvyCodeR Nerd Font Mono"
normal.family = "DroidSansM Nerd Font"

size = 14
