" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.
let os = substitute(system('uname'), "\n", "", "")
if os == "Darwin"
  set gfn=Menlo\ Regular:h12
else
  set guifont=Monospace\ 9            " Font family and font size.
endif

colorscheme cobalt
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
"set guioptions-=T                 " Hide toolbar.
set background=dark              " Background.
set lines=25 columns=100          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar
set nomousehide                   "don't hide the mouse -- very annoying otherwise
set t_vb=                         "screen flashing due to visual bell is driving me nuts


